### ISSUE TITLE
Erreurs avec docker

### ISSUE THREAD

**Issue by Safenein** [kernoeb/PlanningSup#83]
J'ai installé pnpm et lancé la commande `pnpm run dev`. J'ai aussi tenté d'allumer mongoDB avec `docker-compose -f docker-compose-dev.yml up -d` mais cela ne règle pas l'erreur.

L'erreur obtenue au moment de la connexion est la suivante : 
``` 
[13:39:22] [index.js] › ✖  error     Error while initializing mongo MongooseServerSelectionError: getaddrinfo ENOTFOUND mongodb
    at NativeConnection.Connection.openUri (/home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongoose/lib/connection.js:824:32)
    at /home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongoose/lib/index.js:381:10
    at /home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongoose/lib/index.js:380:20)
    at Object.<anonymous> (/home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/server/index.js:20:12)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { 'mongodb:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
[13:39:22] [index.js] › ✖  error     Error: Error connecting to db: getaddrinfo ENOTFOUND mongodb 
    at /home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/connect-mongodb-session/index.js:88:17
    at /home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongodb/lib/utils.js:361:17
    at /home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongodb/lib/mongo_client.js:116:28
    at connectCallback (/home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongodb/lib/operations/connect.js:29:9)
    at /home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongodb/lib/operations/connect.js:79:20
    at exitWithError (/home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongodb/lib/sdam/topology.js:186:53)
    at /home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongodb/lib/sdam/topology.js:190:59
    at /home/<psueudonyme>/Documents/Repositories/PlanningSup-PEI2/node_modules/mongodb/lib/sdam/topology.js:242:80
    at <anonymous>
```

Il n'y a pas d'erreurs avant. C'est uniquement au moment de la connexion avec le navigateur. L'UI s'affiche mais les emplois du temps ne chargent pas.

Testé sur Archlinux, système à jour, node v16, avec pnpm.

**Comment by Safenein** [comment]
J'ai aussi une autre erreur sur Windows, mais je verrai plus tard car je n'ai pas la machine sous la main pour le moment.

**Comment by kernoeb** [comment]
Comme l'indique l'erreur : `getaddrinfo ENOTFOUND mongodb`, Node.js ne trouve pas "mongodb". 

En effet, pour un environnement de production, la valeur a saisir dans le fichier `.env` est bien `mongodb`. À moins d'ajouter cela dans ton `/etc/hosts` (je déconseille), il faut alors remplacer cela par `localhost:27017` en environnement de développement !

`mongodb:27017` n'est utilisé qu'en contexte Docker, au sein d'un même réseau Docker :)

**Comment by Dyskal** [comment]
> J'ai aussi une autre erreur sur Windows, mais je verrai plus tard car je n'ai pas la machine sous la main pour le moment.

faut changer (retirer) le lien vers /opt/planning_v2, sur windows /opt n'existe pas
